### ISSUE TITLE
长时间阅读，突然返回上一页会 crash

### ISSUE THREAD

**Issue by martinx** [kanmaoxian/issues#11]
一直保持阅读状态，半小时到一小时，然后返回上一页，就会提示 crash，出现了两次

~~等下次我将日志贴出来~~

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference
 at android.view.ViewGroup.removeViewsInternal(ViewGroup.java:4692)
 at android.view.ViewGroup.removeViewsInLayout(ViewGroup.java:4540)
 at com.facebook.react.views.view.ReactViewGroup.updateSubviewClipStatus(ReactViewGroup.java:309)
 at com.facebook.react.views.view.ReactViewGroup.updateClippingToRect(ReactViewGroup.java:285)
 at com.facebook.react.views.view.ReactViewGroup.updateClippingRect(ReactViewGroup.java:278)
 at com.facebook.react.views.scroll.ReactHorizontalScrollView.updateClippingRect(ReactHorizontalScrollView.java:195)
 at com.facebook.react.views.scroll.ReactHorizontalScrollView.onScrollChanged(ReactHorizontalScrollView.java:115)
 at android.widget.HorizontalScrollView.onOverScrolled(HorizontalScrollView.java:757)
 at android.view.View.overScrollBy(View.java:19889)
 at android.widget.HorizontalScrollView.computeScroll(HorizontalScrollView.java:1292)
 at android.view.View.updateDisplayListIfDirty(View.java:15185)
 at android.view.View.draw(View.java:15971)
 at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
 at android.view.View.draw(View.java:16204)
 at android.view.View.updateDisplayListIfDirty(View.java:15198)
 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
 at android.view.View.updateDisplayListIfDirty(View.java:15158)
 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
 at android.view.View.updateDisplayListIfDirty(View.java:15158)
 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
 at android.view.View.updateDisplayListIfDirty(View.java:15158)
 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
 at android.view.View.updateDisplayListIfDirty(View.java:15158)
 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
 at android.view.View.updateDisplayListIfDirty(View.java:15158)
 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
 at android.view.View.updateDisplayListIfDirty(View.java:15158)
 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3594)
 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3574)
 at android.view.View.updateDisplayListIfDirty(View.java:15158)
 at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:283)
 at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:289)
 at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:324)
 at android.view.ViewRootImpl.draw(ViewRootImpl.java:2642)
 at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2461)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2094)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6050)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
 at android.view.Choreographer.doCallbacks(Choreographer.java:672)
 at android.view.Choreographer.doFrame(Choreographer.java:608)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
 at android.os.Handler.handleCallback(Handler.java:742)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:154)
 at android.app.ActivityThread.main(ActivityThread.java:5469)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```

**Comment by serco-chen** [comment]
Known issue caused by React Native ScrollView `removeClippedSubviews` flag.
